### PR TITLE
Implement operators from #57 

### PR DESCRIPTION
**Pull request by andreoss**

### CODE REVIEW

**Comment by masak** [comment]
Nice, relational operators!

Hm, but there's a lot going on in this branch.

I'm not sure I want to merge the REPL work as-is &mdash; chiefly because I think it provides an objectively worse experience than just using bash, which has working up/down arrows, history, etc, to give the illusion of editing a one-liner. I'd rather we do [something like this](https://gist.github.com/masak/389f258a527dedcafcfe).

Array concatenation is introduced (but not mentioned in a commit message. (!) The consensus from #57 is that we'll not do it as an operator, but as a `concat(a1, a2)` function.

If this pull request was only the relational operators, I would pull it in immediately. As it stands now, I have some caveats. :)

**Comment by masak** [comment]
Looks mostly good (but see comment about bogus-seeming commit).

May I suggest the following names for the relationals?

* `Q::Infix::Lt`
* `Q::Infix::Le`
* `Q::Infix::Gt`
* `Q::Infix::Ge`

Partly because this rhymes well with `Q::Infix::Eq`. (And on second thought we should probably rename `s/NotEq/Ne/`. Partly because there's prior art that we can tap into from bash/Perl.

**Comment by masak** [comment]
Rebased locally (for a cleaner history) and merged. Thanks!

Two comments:

* I don't see offhand why [this test](https://github.com/andreoss/007/commit/ee669895e3d4eb25712ca6554f878890ba19049b#diff-88a45548df2c7691e7f68357d8578557R417) needed to move aside for the new operator. I'm sure there was a reason; I haven't checked. I suspect the reason is wrong, though, and there's a bug there which could use a test.

* See the last point of [this comment](https://github.com/masak/007/pull/103#issuecomment-166325771) &mdash; we will end up making `infix:<||>` and `infix:<&&>` short-circuiting.

Closing.

**Comment by vendethiel** [comment]
Is `!0!` parsed correctly?

**Comment by masak** [comment]
Should be. See opearators.md in the repo for an explanation.

**Pull request closed without merging**
